### ISSUE TITLE
Usage with Python selenium

### ISSUE THREAD

**Issue by mike-fmh** [nanasess/setup-chromedriver#13]
Is it possible to use this instance of chromedriver in github actions with a python seleium script? If so, what is the path to the chromedriver?

**Comment by nanasess** [comment]
@mike-fmh google-chrome  must be installed beforehand.

e.g

```yaml
- uses: actions/checkout@master
- run: sudo apt-fast install -y google-chrome
- uses: nanasess/setup-chromedriver@master
```
