### ISSUE TITLE
Action always installs latest chrome even for older chromedriver

### ISSUE THREAD

**Issue by kunalherkal** [nanasess/setup-chromedriver#244]
Action usage:
```
    - name: Set up chromedriver
      uses: nanasess/setup-chromedriver@v2
      with:
        chromedriver-version: 118.0.5993.70
```
This still installs Chrome 119 which then causes issues in selenium tests.
Expectation: It should install Chrome 118.

**Comment by danielaboost** [comment]
Is there a work-around for this?

**Comment by nanasess** [comment]
@kunalherkal @danielaboost 
If google-chrome is not installed, google-chrome-stable will be installed.
You can avoid this by installing google-chrome 118 beforehand.

**Comment by nanasess** [comment]
Hi @kunalherkal @danielaboost — this is working as designed: when `google-chrome` isn't already installed, the action installs the latest `google-chrome-stable`; it does not install a Chrome build that matches a pinned `chromedriver-version`. The intended way to control the Chrome version is to install the Chrome you want **before** this step (e.g. [browser-actions/setup-chrome](https://github.com/browser-actions/setup-chrome)) and then pin `chromedriver-version` to match it.

```yaml
- uses: browser-actions/setup-chrome@v1
  with:
    chrome-version: '118'
- uses: nanasess/setup-chromedriver@v2
  with:
    chromedriver-version: '118.0.5993.70'
```

Closing as working-as-intended with that workaround — happy to revisit if there's a concrete need for the action itself to install a specific older Chrome.
