### ISSUE TITLE
Make CHROMEAPP an input variable that can be declared from the GitHub action workflow

### ISSUE THREAD

**Issue by afernandez-01** [nanasess/setup-chromedriver#252]
Make CHROMEAPP an a input variable that can be declared from the GitHub action workflow. https://github.com/nanasess/setup-chromedriver/blob/be2079a2aee95708f7e32eeb78c6c261ed087297/lib/setup-chromedriver.sh#L14

Action Usage
```
      - name: Selenium ChromeDriver - Install
        if: ${{ inputs.install_selenium }}
        uses: nanasess/setup-chromedriver@v2.2.1
        id: setup-chromedriver
        with:
          chromedriver-version: '119.0.6045.105'
```
Its failing to find google-chrome with the command `dpkg -s google-chrome`
```
runner@fd37d0ad3433:/$ dpkg -s google-chrome
dpkg-query: package 'google-chrome' is not installed and no information is available
Use dpkg --info (= dpkg-deb --info) to examine archive files.
runner@fd37d0ad3433:/$ dpkg -s google-chrome-stable
Package: google-chrome-stable
Status: install ok installed
Priority: optional
Section: web
Installed-Size: 326369
Maintainer: Chrome Linux Team <chromium-dev@chromium.org>
Architecture: amd64
Version: 119.0.6045.159-1
Provides: www-browser
Depends: ca-certificates, fonts-liberation, libasound2 (>= 1.0.17), libatk-bridge2.0-0 (>= 2.5.3), libatk1.0-0 (>= 2.2.0), libatspi2.0-0 (>= 2.9.90), libc6 (>= 2.17), libcairo2 (>= 1.6.0), libcups2 (>= 1.6.0), libcurl3-gnutls | libcurl3-nss | libcurl4 | libcurl3, libdbus-1-3 (>= 1.9.14), libdrm2 (>= 2.4.75), libexpat1 (>= 2.1~beta3), libgbm1 (>= 17.1.0~rc2), libglib2.0-0 (>= 2.39.4), libgtk-3-0 (>= 3.9.10) | libgtk-4-1, libnspr4 (>= 2:4.9-2~), libnss3 (>= 2:3.35), libpango-1.0-0 (>= 1.14.0), libu2f-udev, libvulkan1, libx11-6 (>= 2:1.4.99.1), libxcb1 (>= 1.9.2), libxcomposite1 (>= 1:0.4.4-1), libxdamage1 (>= 1:1.1), libxext6, libxfixes3, libxkbcommon0 (>= 0.5.0), libxrandr2, wget, xdg-utils (>= 1.0.2)
Pre-Depends: dpkg (>= 1.14.0)
Description: The web browser from Google
 Google Chrome is a browser that combines a minimal design with sophisticated technology to make the web faster, safer, and easier.
runner@fd37d0ad3433:/$
```
Making this an optional input variable will give the ability to pass in google-chrome-stable as the CHROMEAPP.
