### ISSUE TITLE
Unable to install Chrome driver 126.0.6478.62

### ISSUE THREAD

**Issue by tsundberg** [nanasess/setup-chromedriver#318]
When I specify the chromedriver-version to be 126.0.6478.62 like this:
```
    steps:
      - uses: nanasess/setup-chromedriver@v2
        with:
          # Optional: do not specify to match Chrome's version
          chromedriver-version: '126.0.6478.62'
      - name: Setup Chromedriver matching the installed Chrome version
        run: |
          export DISPLAY=:99
          chromedriver --url-base=/wd/hub &
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional

```

Then my GitHub action fails with the error message

```
Run nanasess/setup-chromedriver@v2
##setup chromedriver
/home/runner/work/_actions/nanasess/setup-chromedriver/v2/lib/setup-chromedriver.sh  linux64
dpkg-query: package 'google-chrome' is not installed and no information is available
Use dpkg --info (= dpkg-deb --info) to examine archive files.
Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8)).
Executing: /tmp/apt-key-gpghome.DOxUGGXpWH/gpg.1.sh --keyserver keyserver.ubuntu.com --recv-keys 4EB27DB2A3B88B8B
gpg: keyserver receive failed: Network is unreachable
Error: The process '/home/runner/work/_actions/nanasess/setup-chromedriver/v2/lib/setup-chromedriver.sh' failed with exit code 2
```
Here is a screenshot of the same error as above:

![image](https://github.com/nanasess/setup-chromedriver/assets/541840/6a2677d9-0b7d-4d72-9f15-f7811419460f)

Please advice on how to get hold of the latest chromedriver-version as specified here: https://googlechromelabs.github.io/chrome-for-testing/
