### ISSUE TITLE
Error `sudo: command not found`

### ISSUE THREAD

**Issue by marcandre** [nanasess/setup-chromedriver#32]
I'm trying to install chromedriver on Github actions, but getting:

```
Run nanasess/setup-chromedriver@master
  with:
    chromedriver-version: 88.0.4324.96
/usr/bin/docker exec  09fd831c857ab493aa5bdd18081d4d0f2275269062204f74c4f050c7276a208e sh -c "cat /etc/*release | grep ^ID"
##setup chromedriver
/__w/_actions/nanasess/setup-chromedriver/master/lib/setup-chromedriver.sh 88.0.4324.96 linux64
/__w/_actions/nanasess/setup-chromedriver/master/lib/setup-chromedriver.sh: line 11: sudo: command not found
Error: The process '/__w/_actions/nanasess/setup-chromedriver/master/lib/setup-chromedriver.sh' failed with exit code 127
```

Our workflow looks like this:

```yaml
name: Review

on:
  pull_request:
jobs:
  review:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    container:
      image: elixir:1.12.1-slim
    services:
      postgis:
        image: mdillon/postgis:11
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_HOST: "/"
    steps:
    - uses: actions/checkout@v2
    - uses: nanasess/setup-chromedriver@master
      with:
        # Optional: do not specify to match Chrome's version
        chromedriver-version: '88.0.4324.96'
```

I tried without the `with: ...`, same result.

Any idea?
