### ISSUE TITLE
1.0.6 broke use with github action @v1

### ISSUE THREAD

**Issue by zswanson** [nanasess/setup-chromedriver#40]
We have our github action set to v1 and just started seeing the following error in workflow logs

Run nanasess/setup-chromedriver@v1
internal/modules/cjs/loader.js:818
  throw err;
  ^

Error: Cannot find module './oidc-utils'
Require stack:
- /home/runner/work/_actions/nanasess/setup-chromedriver/v1/node_modules/@actions/core/lib/core.js
- /home/runner/work/_actions/nanasess/setup-chromedriver/v1/lib/setup-chromedriver.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:1[9](https://github.com/seniorlink-vela/auth-web/runs/5603909533?check_suite_focus=true#step:4:9))
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/runner/work/_actions/nanasess/setup-chromedriver/v1/node_modules/@actions/core/lib/core.js:37:22)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:[10](https://github.com/seniorlink-vela/auth-web/runs/5603909533?check_suite_focus=true#step:4:10)27:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:[14](https://github.com/seniorlink-vela/auth-web/runs/5603909533?check_suite_focus=true#step:4:14))
    at Module.require (internal/modules/cjs/loader.js:887:[19](https://github.com/seniorlink-vela/auth-web/runs/5603909533?check_suite_focus=true#step:4:19)) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/runner/work/_actions/nanasess/setup-chromedriver/v1/node_modules/@actions/core/lib/core.js',
    '/home/runner/work/_actions/nanasess/setup-chromedriver/v1/lib/setup-chromedriver.js'
  ]
}

Relevant portion of the github workflow
```
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: yarn

      - name: Setup chromium driver for tests
        uses: nanasess/setup-chromedriver@v1
```
