### ISSUE TITLE
google-chrome is not installed when used in github actions

### ISSUE THREAD

**Issue by ghost** [nanasess/setup-chromedriver#7]
Run nanasess/setup-chromedriver@master
`/usr/bin/docker exec  ecfce479f2448e9e04f32d9483aa598c9ddfa34d0c7cf4c35c7520c1a152e61e sh -c "cat /etc/*release | grep ^ID"`
Running JavaScript Action with default external tool: node12
##setup chromedriver
/__w/_actions/nanasess/setup-chromedriver/master/lib/setup-chromedriver.sh  linux64
/__w/_actions/nanasess/setup-chromedriver/master/lib/setup-chromedriver.sh: line 9: **google-chrome: command not found**

**Comment by nanasess** [comment]
@jethro-riosa Welcome to setup-chromedriver, thanks for the detailed issue.
Please tell me the architecture and version in which the problem occurred.

**Comment by nanasess** [comment]
@jethro-riosa google-chrome  must be installed beforehand.

e.g

```yaml
- uses: actions/checkout@master
- run: sudo apt-fast install -y google-chrome
- uses: nanasess/setup-chromedriver@master
```
